GET http://localhost:5263

###
GET http://localhost:5263/users

###
GET http://localhost:5263/users/1

###
POST http://localhost:5263/users
Content-Type: application/json

{
  "Name": "David",
  "Email": "david@example.com",
  "Role": "User",
  "AccountBalance": 100.00,
  "CreatedDate": "2023-04-01"
}

###
PUT http://localhost:5263/users/3
Content-Type: application/json

{
    "Name": "Charlie 123412",
    "Email": "charlie.updated@example.com",
    "Role": "Admin",
    "AccountBalance": 3.50,
    "CreatedDate": "2023-03-01"
}

###
DELETE http://localhost:5263/users/4

### try to get user 4 info when not created
GET  http://localhost:5263/users/4

### try to update user 5 throught it not existed
PUT http://localhost:5263/users/5
Content-Type: application/json

{
    "Name": "Charlie 123412",
    "Email": "charlie.updated@example.com",
    "Role": "User",
    "AccountBalance": 3.50,
    "CreatedDate": "2023-03-01"
}

###
POST http://localhost:5263/users
Content-Type: application/json

{
  "Name": "",
  "Email": "blankUserName@example.com",
  "Role": "User",
  "AccountBalance": 100.00,
  "CreatedDate": "2023-04-01"
}

###
POST http://localhost:5263/users
Content-Type: application/json

{
  "Name": "hhh",
  "Email": "ThisIsAVeryLongEmailThatExceedsTheMaximumAllowedLength@example.com",
  "Role": "User",
  "AccountBalance": 100.00,
  "CreatedDate": "2023-04-01"
}

###
POST http://localhost:5263/users
Content-Type: application/json

{
  "Name": "Invalid Balance",
  "Email": "t@example.com",
  "Role": "User",
  "AccountBalance": -100.00,
  "CreatedDate": "2023-04-01"
}


